-- Enable useful extensions for search + case-insensitive comparisons.
create extension if not exists pg_trgm;
create extension if not exists unaccent;
create extension if not exists pgcrypto;

-- Enums
create type "NoteStatus" as enum ('ACTIVE', 'ARCHIVED', 'TRASH');
create type "NoteMemberRole" as enum ('OWNER', 'EDITOR', 'VIEWER');
create type "SharePermission" as enum ('VIEW', 'COMMENT', 'EDIT');
create type "SortOrder" as enum ('ASC', 'DESC');
create type "SavedViewSortBy" as enum ('UPDATED_AT', 'CREATED_AT');

-- Core user profile table (id should match Supabase auth user id UUID)
create table "user_profiles" (
  "id" uuid primary key,
  "email" text unique,
  "displayName" varchar(120),
  "avatarUrl" text,
  "timezone" varchar(64) default 'UTC',
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table "notes" (
  "id" uuid primary key default gen_random_uuid(),
  "ownerId" uuid not null,
  "title" varchar(255) not null default 'Untitled note',
  "body" text not null default '',
  "status" "NoteStatus" not null default 'ACTIVE',
  "color" varchar(32),
  "isPinned" boolean not null default false,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  "lastEditedAt" timestamptz not null default now(),
  "archivedAt" timestamptz,
  "deletedAt" timestamptz,
  constraint "notes_ownerId_fkey"
    foreign key ("ownerId") references "user_profiles"("id")
    on delete cascade on update cascade
);

create table "tags" (
  "id" uuid primary key default gen_random_uuid(),
  "ownerId" uuid not null,
  "name" varchar(64) not null,
  "slug" varchar(64) not null,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  constraint "tags_ownerId_fkey"
    foreign key ("ownerId") references "user_profiles"("id")
    on delete cascade on update cascade
);

create table "note_tags" (
  "noteId" uuid not null,
  "tagId" uuid not null,
  "createdAt" timestamptz not null default now(),
  primary key ("noteId", "tagId"),
  constraint "note_tags_noteId_fkey"
    foreign key ("noteId") references "notes"("id")
    on delete cascade on update cascade,
  constraint "note_tags_tagId_fkey"
    foreign key ("tagId") references "tags"("id")
    on delete cascade on update cascade
);

create table "saved_views" (
  "id" uuid primary key default gen_random_uuid(),
  "ownerId" uuid not null,
  "name" varchar(120) not null,
  "searchQuery" text not null default '',
  "tagSlugs" text[] not null default '{}',
  "statuses" "NoteStatus"[] not null default array['ACTIVE']::"NoteStatus"[],
  "sortBy" "SavedViewSortBy" not null default 'UPDATED_AT',
  "sortOrder" "SortOrder" not null default 'DESC',
  "updatedWithinDays" integer,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  constraint "saved_views_ownerId_fkey"
    foreign key ("ownerId") references "user_profiles"("id")
    on delete cascade on update cascade
);

create table "note_members" (
  "noteId" uuid not null,
  "userId" uuid not null,
  "role" "NoteMemberRole" not null default 'EDITOR',
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  primary key ("noteId", "userId"),
  constraint "note_members_noteId_fkey"
    foreign key ("noteId") references "notes"("id")
    on delete cascade on update cascade,
  constraint "note_members_userId_fkey"
    foreign key ("userId") references "user_profiles"("id")
    on delete cascade on update cascade
);

create table "share_links" (
  "id" uuid primary key default gen_random_uuid(),
  "noteId" uuid not null,
  "token" varchar(64) not null unique,
  "permission" "SharePermission" not null default 'VIEW',
  "createdById" uuid not null,
  "expiresAt" timestamptz,
  "revokedAt" timestamptz,
  "lastAccessAt" timestamptz,
  "createdAt" timestamptz not null default now(),
  constraint "share_links_noteId_fkey"
    foreign key ("noteId") references "notes"("id")
    on delete cascade on update cascade,
  constraint "share_links_createdById_fkey"
    foreign key ("createdById") references "user_profiles"("id")
    on delete cascade on update cascade
);

create table "note_versions" (
  "id" bigint generated by default as identity primary key,
  "noteId" uuid not null,
  "authorId" uuid,
  "title" varchar(255) not null,
  "body" text not null,
  "createdAt" timestamptz not null default now(),
  constraint "note_versions_noteId_fkey"
    foreign key ("noteId") references "notes"("id")
    on delete cascade on update cascade,
  constraint "note_versions_authorId_fkey"
    foreign key ("authorId") references "user_profiles"("id")
    on delete set null on update cascade
);

-- Required indexes for filters + cursor pagination + joins.
create unique index "tags_owner_slug_unique" on "tags" ("ownerId", "slug");
create unique index "saved_views_owner_name_unique" on "saved_views" ("ownerId", "name");
create index "notes_owner_status_updated_id_idx" on "notes" ("ownerId", "status", "updatedAt" desc, "id" desc);
create index "notes_owner_status_created_id_idx" on "notes" ("ownerId", "status", "createdAt" desc, "id" desc);
create index "tags_owner_name_idx" on "tags" ("ownerId", "name");
create index "note_tags_tag_note_idx" on "note_tags" ("tagId", "noteId");
create index "saved_views_owner_updated_idx" on "saved_views" ("ownerId", "updatedAt" desc);
create index "note_members_user_role_idx" on "note_members" ("userId", "role");
create index "share_links_note_created_idx" on "share_links" ("noteId", "createdAt" desc);
create index "share_links_token_revoked_idx" on "share_links" ("token", "revokedAt");
create index "note_versions_note_created_idx" on "note_versions" ("noteId", "createdAt" desc);

-- Full-text search support for title + body.
alter table "notes" add column "search_vector" tsvector
generated always as (
  setweight(to_tsvector('simple', coalesce("title", '')), 'A') ||
  setweight(to_tsvector('simple', coalesce("body", '')), 'B')
) stored;

create index "notes_search_vector_idx" on "notes" using gin ("search_vector");
create index "notes_title_trgm_idx" on "notes" using gin ("title" gin_trgm_ops);
create index "notes_body_trgm_idx" on "notes" using gin ("body" gin_trgm_ops);

-- Keep updatedAt accurate for SQL-level writes.
create or replace function set_timestamp_updated_at()
returns trigger as $$
begin
  new."updatedAt" = now();
  return new;
end;
$$ language plpgsql;

create trigger set_user_profiles_updated_at
before update on "user_profiles"
for each row execute function set_timestamp_updated_at();

create trigger set_notes_updated_at
before update on "notes"
for each row execute function set_timestamp_updated_at();

create trigger set_tags_updated_at
before update on "tags"
for each row execute function set_timestamp_updated_at();

create trigger set_saved_views_updated_at
before update on "saved_views"
for each row execute function set_timestamp_updated_at();

create trigger set_note_members_updated_at
before update on "note_members"
for each row execute function set_timestamp_updated_at();
